### ISSUE TITLE
Problems parsing lists of lists? [rt.cpan.org #62077]

### ISSUE THREAD

**Issue by toddr** [toddr/YAML-Syck#40]
Migrated from [rt.cpan.org#62077](https://rt.cpan.org/Ticket/Display.html?id=62077) (status was 'stalled')

Requestors:
* ambs@cpan.org

Attachments:
* [port.yaml](https://rt.cpan.org/Ticket/Attachment/842087/436024/port.yaml)

From ambs@cpan.org on 2010-10-12 12:54:45:
```
The document in attach fails parsing...

This is specially bad because one can't easily choose the backend with
YAML::Any.

Thanks
```

**Comment by toddr** [comment]
```yaml
META:
 LANG: Português
 VARIANT: Europeu
 IDS: [port, pt, pt_PT]
 SNDCLASSES: [[x,ch],[ss,o]]
```
